# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d06b26c96a03c3b2174aef5d84cd62b690785a82be6117d1d6b5b1dae636e3f7bac9a60153e08bbcfd0595ba90167379cbe01baa52fe3b6ddc8c30110bb36b5

test:
  secret_key_base: 6322ba5f4cfb76fb128e629d7c4e896a7a107a2d33ec092d62d9607eededcd357c5f18879ba513d9f2de05d795bf6541dca6d80ce15df82f99adb3ff5247926b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
